config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def new
    @article = Article.new()
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_show(@article)
  end

  private
  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def about

  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/new.html.erb
<h1>Create an Article</h1>

<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>
  About my Alpha Blog
</h1>

<div style="border: 1px solid black;padding: 25px;">
  <%= link_to 'Home', root_path %>
  <%= link_to 'About', about_path %>
</div>

<p>
  This is the about page of my Blog
</p>
<img src='https://2.bp.blogspot.com/-9ZSCHLTXEKM/WE-hKpSivhI/AAAAAAAAVJ0/0xwD5EM8bcUsLaz7IQbm8huHAeYJvTaXQCLcB/s1600/Dwarf-Undead-Battle-Scene.jpg' style="width:100%;height;auto;">

app/views/pages/home.html.erb
<h1>
  Welcome to my Alpha Blog!!!
</h1>

<div style="border: 1px solid black;padding: 25px;">
  <%= link_to 'Home', root_path %>
  <%= link_to 'About', about_path %>
</div>

<p>
  This is the home page of my Blog
</p>
<img src='https://2.bp.blogspot.com/-9ZSCHLTXEKM/WE-hKpSivhI/AAAAAAAAVJ0/0xwD5EM8bcUsLaz7IQbm8huHAeYJvTaXQCLcB/s1600/Dwarf-Undead-Battle-Scene.jpg' style="width:100%;height;auto;">